openapi: 3.0.0
info:
  title: Blog API - INF222
  version: 1.0.0
  description: API pour le TAF1 de développement Backend
paths:
  /api/articles:
    get:
      summary: Liste tous les articles
      responses:
        '200':
          description: Succès
    post:
      summary: Créer un article
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titre: {type: string}
                contenu: {type: string}
                auteur: {type: string}
